model mgmt vuln

diff --git a/assets/training/model_management/components/convert_model_to_mlflow/spec.yaml b/assets/training/model_management/components/convert_model_to_mlflow/spec.yaml
--- a/assets/training/model_management/components/convert_model_to_mlflow/spec.yaml
+++ b/assets/training/model_management/components/convert_model_to_mlflow/spec.yaml
@@ -1,7 +1,7 @@
 $schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
 
 name: convert_model_to_mlflow
-version: 0.0.17
+version: 0.0.18
 type: command
 
 is_deterministic: True
@@ -9,10 +9,16 @@ is_deterministic: True
 display_name: Convert models to MLflow
 description: Component converts models from supported frameworks to MLflow model packaging format
 
-environment: azureml://registries/azureml/environments/model-management/versions/17
+environment: azureml://registries/azureml/environments/model-management/versions/18
 
 code: ../../src/
 command: >
+  set -e
+  IFS=',' read -ra pip_pkgs <<< "$[[inputs.hf_use_experimental_features]]"
+  pip_pkg_str="${pip_pkgs[*]}"
+  if [[ -n "$pip_pkg_str" ]]; then echo "Installing $pip_pkg_str"; pip install $pip_pkg_str
+  echo "pip installation completed. For any installation error please check above logs"
+  fi 
   python run_model_preprocess.py
   $[[--model-id ${{inputs.model_id}}]]
   $[[--task-name ${{inputs.task_name}}]]
