[DBCopilot] upgrade package

diff --git a/assets/large_language_models/dbcopilot/environments/dbcopilot_grounding/context/Dockerfile b/assets/large_language_models/dbcopilot/environments/dbcopilot_grounding/context/Dockerfile
--- a/assets/large_language_models/dbcopilot/environments/dbcopilot_grounding/context/Dockerfile
+++ b/assets/large_language_models/dbcopilot/environments/dbcopilot_grounding/context/Dockerfile
@@ -15,7 +15,7 @@ USER root
 # ODBC
 # adding custom MS repository
 RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
-RUN curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list
+RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
 
 # install SQL Server drivers
 # install SQL Server tools
@@ -23,7 +23,92 @@ RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
 RUN echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
 RUN /bin/bash -c "source ~/.bashrc"
 
-
 # Workaround: install packages with extra index url. Will be removed after the packages are published to pypi
-RUN pip install https://ragsample.blob.core.windows.net/ragdata/wheels/dbcopilot/dbcopilot-0.3.20230613.dev4-py3-none-any.whl
-RUN pip install https://ragsample.blob.core.windows.net/ragdata/wheels/dbcopilot/db_copilot_tool-0.1.3-py3-none-any.whl
+RUN pip install https://ragsample.blob.core.windows.net/ragdata/wheels/dbcopilot/dbcopilot-0.3.20230704.3-py3-none-any.whl
+RUN pip install https://ragsample.blob.core.windows.net/ragdata/wheels/dbcopilot/db_copilot_tool-0.1.6-py3-none-any.whl
+
+# Install promptflow
+RUN pip install https://ragsample.blob.core.windows.net/ragdata/wheels/dbcopilot/promptflow_sdk-0.0.99116360-py3-none-any.whl
+RUN pip install https://ragsample.blob.core.windows.net/ragdata/wheels/dbcopilot/prompt_flow_tools-0.0.3-py3-none-any.whl
+
+# Install embeddingstore sdk
+RUN pip install https://ragsample.blob.core.windows.net/ragdata/wheels/dbcopilot/embeddingstore-0.0.99061601-py3-none-any.whl
+
+
+RUN set -eux; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+    # utilities for keeping Debian and OpenJDK CA certificates in sync
+    ca-certificates p11-kit wget \
+    ; \
+    rm -rf /var/lib/apt/lists/*
+
+ENV JAVA_HOME /usr/local/openjdk-21
+ENV PATH $JAVA_HOME/bin:$PATH
+
+# Default to UTF-8 file.encoding
+ENV LANG C.UTF-8
+
+# https://jdk.java.net/
+# >
+# > Java Development Kit builds, from Oracle
+# >
+ENV JAVA_VERSION 21-ea+22
+
+RUN set -eux; \
+    \
+    arch="$(dpkg --print-architecture)"; \
+    case "$arch" in \
+    'amd64') \
+    downloadUrl='https://download.java.net/java/early_access/jdk21/25/GPL/openjdk-21-ea+25_linux-x64_bin.tar.gz'; \
+    downloadSha256='26d0ae26838de257ddb7dc06e11eee28038678adf85c494686c6592ff027a0b4'; \
+    ;; \
+    *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
+    esac; \
+    \
+    savedAptMark="$(apt-mark showmanual)"; \
+    \
+    wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; \
+    echo "$downloadSha256 *openjdk.tgz" | sha256sum --strict --check -; \
+    \
+    mkdir -p "$JAVA_HOME"; \
+    tar --extract \
+    --file openjdk.tgz \
+    --directory "$JAVA_HOME" \
+    --strip-components 1 \
+    --no-same-owner \
+    ; \
+    rm openjdk.tgz*; \
+    \
+    apt-mark auto '.*' > /dev/null; \
+    [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null; \
+    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=true; \
+    \
+    # update "cacerts" bundle to use Debian's CA certificates (and make sure it stays up-to-date with changes to Debian's store)
+    # see https://github.com/docker-library/openjdk/issues/327
+    #     http://rabexc.org/posts/certificates-not-working-java#comment-4099504075
+    #     https://salsa.debian.org/java-team/ca-certificates-java/blob/3e51a84e9104823319abeb31f880580e46f45a98/debian/jks-keystore.hook.in
+    #     https://git.alpinelinux.org/aports/tree/community/java-cacerts/APKBUILD?id=761af65f38b4570093461e6546dcf6b179d2b624#n29
+    mkdir -p /etc/ca-certificates/update.d; \
+    ls -al /etc/ca-certificates; \
+    { \
+    echo '#!/usr/bin/env bash'; \
+    echo 'set -Eeuo pipefail'; \
+    echo 'trust extract --overwrite --format=java-cacerts --filter=ca-anchors --purpose=server-auth "$JAVA_HOME/lib/security/cacerts"'; \
+    } > /etc/ca-certificates/update.d/docker-openjdk; \
+    chmod +x /etc/ca-certificates/update.d/docker-openjdk; \
+    /etc/ca-certificates/update.d/docker-openjdk; \
+    update-ca-certificates; \
+    \
+    # https://github.com/docker-library/openjdk/issues/331#issuecomment-498834472
+    find "$JAVA_HOME/lib" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf; \
+    ldconfig; \
+    \
+    # https://github.com/docker-library/openjdk/issues/212#issuecomment-420979840
+    # https://openjdk.java.net/jeps/341
+    java -Xshare:dump; \
+    \
+    # basic smoke test
+    fileEncoding="$(echo 'System.out.println(System.getProperty("file.encoding"))' | jshell -s -)"; [ "$fileEncoding" = 'UTF-8' ]; rm -rf ~/.java; \
+    javac --version; \
+    java --version
