Ensure list of assets isn't empty

diff --git a/.github/workflows/assets-release.yaml b/.github/workflows/assets-release.yaml
--- a/.github/workflows/assets-release.yaml
+++ b/.github/workflows/assets-release.yaml
@@ -65,8 +65,7 @@ jobs:
     
       - name: Install dependencies
         run: pip install -e $main_dir/$scripts_azureml_assets_dir
-      
-      # TODO: Consider using Git to detect changes
+
       - name: Find updated assets
         id: find-updated-assets
         run: python -u $scripts_assets_dir/update_assets.py -i "$asset_dirs" -r ${{ github.workspace }}/$release_dir -o ${{ runner.temp }}/$changed_assets_artifact
@@ -89,12 +88,19 @@ jobs:
             !${{ runner.temp }}/${{ env.changed_assets_artifact }}/environment
       
       - name: Create list of assets
+        id: create-assets-list
         run: |
           artifact_dir=${{ runner.temp }}/$asset_list_artifact
           mkdir -p $artifact_dir
           python -u $scripts_assets_dir/asset_utils.py list -i "$asset_dirs" -o $artifact_dir/$asset_list_file
         working-directory: ${{ env.main_dir }}
-      
+
+      - name: Check list of assets
+        if: steps.create-assets-list.outputs.asset_count == 0
+        run: |
+          echo "::error::List of assets is empty. Please check the main branch and this workflow."
+          exit 1
+
       - name: Upload list of artifacts
         uses: actions/upload-artifact@v3
         with:
